services:
  nexus:
    image: sonatype/nexus:2.15.2-03
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8082:8081"
      - 5000:5000
    volumes:
      - nexus_data:/nexus-data
volumes:
  nexus_data:
    name: nexus_data